Add metrics exporter and configuration for SystemMetrics
lightstep/otel-launcher-python pull request #41
Opened 2020-09-03 15:43 UTC by ocelotl

Fixes #40

2020-09-04 00:02 UTC, codeboten requested changes
This is a great start, would like to see some unit tests around metrics configuration, requesting for change to ensure we don't merge before the new packages are released.

2020-10-17 23:01 UTC, ocelotl commented on noxfile.py
> +    )
Fixed

2020-10-17 23:02 UTC, ocelotl commented on src/opentelemetry/launcher/configuration.py
> +    if metric_exporter_insecure:
Fixed

2020-11-03 18:16 UTC, codeboten approved these changes
Only missing an update to the README, otherwise looks good

2020-11-03 18:51 UTC, ocelotl commented on src/opentelemetry/launcher/configuration.py
>      metric_exporter_insecure: bool = (_OTEL_EXPORTER_OTLP_METRIC_INSECURE),
fixed

2020-11-03 18:51 UTC, ocelotl commented on src/opentelemetry/launcher/configuration.py
> +        # get_meter(__name__),
fixed

2020-11-03 18:51 UTC, ocelotl commented on src/opentelemetry/launcher/configuration.py
> +    # get_meter,
fixed

2020-11-03 18:51 UTC, ocelotl commented on src/opentelemetry/launcher/configuration.py
> +    "ingest.lightstep.com:443"
fixed

2020-11-03 18:53 UTC, merged